INTERACTIVE_MODELS_PATH: "./experiments/iter_mask/cocolvis_hrnet18s/000_first-try/checkpoints/"
EXPS_PATH: "./experiments"


# Evaluation datasets
GRABCUT_PATH: "./data/datasets/GrabCut"
BERKELEY_PATH: "./data/datasets/Berkeley"
DAVIS_PATH:  "./data/datasets/DAVIS"
COCO_MVAL_PATH: "./data/datasets/COCO_MVal"
PASCALVOC_PATH: "./data/datasets/VOC2012/VOCdevkit/VOC2012"
DAVIS585_PATH: "./data/datasets/InterDavis/Selected_480P"
PANC_MVAL_PATH: "./data/datasets/Panc"

# Train datasets
SBD_PATH:  "./data/datasets/SBD/dataset"
COCO_PATH: "./data/dataset/COCO"
LVIS_PATH: "./data/datasets/COCO_LVIS"
LVIS_v1_PATH: "./data/datasets/COCO_LVIS"
OPENIMAGES_PATH: "./data/dataset/OpenImage"
ADE20K_PATH: "./data/datasets/ADE20K"
PANC_PATH: "./data/datasets/Panc"

# Extra options for training
THINOBJECT_PATH: "./data/datasets/ThinObject/ThinObject5K"
MSRA10K_PATH: "./data/datasets/Saliency/MSRA10K_Imgs_GT/Imgs"
DUT_TR_PATH: "./data/datasets/Saliency/DUTS-TR/DUTS-TR-Image"
DUT_TE_PATH: "./data/datasets/Saliency/DUTS-TE/DUTS-TE-Image"
YTBVOS_PATH: "./data/datasets/YTBVOS"
HFLICKER_PATH: "./data/datasets/HFlickr"


# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./data/weights/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./data/weights/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./data/weights/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./data/weights/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./data/weights/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./data/weights/hrnetv2_w64_imagement_pretrained.pth"
  SEGFORMER_B0: "./data/weights/Segformer/mit_b0.pth"
  SEGFORMER_B1: "./data/weights/Segformer/mit_b1.pth"
  SEGFORMER_B3: "./data/weights/Segformer/mit_b3.pth"
  PPLCNET_X1 : "./data/weights/PPLC/PP-LCNet/PPLCNet_x1_0_ssld_pretrained.pth"
  MOBILENETV2: "./data/weights/mobilenetV2-15498621.pth"











